INSERT INTO PROVEEDOR(ID_PROVEEDOR,NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO)
VALUES(0,'EMMANUEL','ROSALES','SALAS');

INSERT INTO ADDRESS(ID_ADDRESS,PAIS,PROVINCIA,CANTON,DIRECCION_EXACTA)
VALUES(0,'COSTA RICA','ALAJUELA','ATENAS','SABANA LARGA');

SELECT * FROM PROVEEDOR;
SELECT * FROM ADDRESS;