CREATE SEQUENCE S_PRODUCTO
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;
CREATE SEQUENCE S_BODEGA
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;
CREATE SEQUENCE S_TELEFONO
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;      
 
CREATE SEQUENCE S_FACTURA
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;  
CREATE SEQUENCE S_MARCA
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;       
CREATE SEQUENCE S_CATEGORIA
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;
CREATE SEQUENCE S_VENTA
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;    
CREATE SEQUENCE S_HISTORIAL_DE_COMPRAS
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;
CREATE SEQUENCE S_DIRECCION
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;  
CREATE SEQUENCE S_PUNTO_DE_VENTA
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;   
CREATE SEQUENCE S_Pivot
       START WITH 1
       INCREMENT BY 1
       MINVALUE 0
       MAXVALUE 100000000
       NOCACHE
       NOCYCLE;   