CREATE TABLE PROVEEDOR 
(
  ID_PROVEEDOR NUMBER(8) NOT NULL 
, NOMBRE VARCHAR2(25) NOT NULL 
, PRIMER_APELLIDO VARCHAR2(25) NOT NULL 
, SEGUNDO_APELLIDO VARCHAR2(25) NOT NULL 
,CONSTRAINT PROVEEDOR_FK PRIMARY KEY (ID_PROVEEDOR)
       USING INDEX
             TABLESPACE GE_IDX PCTFREE 20
             STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)
      ENABLE 
)
LOGGING 
TABLESPACE GE_TBL
STORAGE (INITIAL 6144
        NEXT 6144
        MINEXTENTS 1
        MAXEXTENTS 5);

COMMENT ON COLUMN PROVEEDOR.ID_PROVEEDOR IS 'COLUMNA QUE POSEE EL ID DEL PROVEEDOR ';
COMMENT ON COLUMN PROVEEDOR.NOMBRE IS 'COLUMNA QUE TIENE EL NOMBRE DEL PROVEEDOR';
COMMENT ON COLUMN PROVEEDOR.PRIMER_APELLIDO IS 'COLUMNA QUE POSEE EL PRIMER APELLIDO DEL PROVEEDOR';
COMMENT ON COLUMN PROVEEDOR.SEGUNDO_PROVEEDOR IS 'COLUMNA QUE POSEE EL SEGUNDO APELLIDO DEL PROVEEDOR';

--- TABLA DIRECCIÓN

CREATE TABLE ADDRESS(
       ID_ADDRESS NUMBER(8)
          CONSTRAINT ID_ADDRESS_NN NOT NULL,
       PAIS VARCHAR2(25)
          CONSTRAINT ADDRESS_PAIS_NN NOT NULL,
       PROVINCIA VARCHAR2(25)
          CONSTRAINT ADDRESS_PROVINCIA_NN NOT NULL,
       CANTON VARCHAR2(25)
          CONSTRAINT ADDRESS_CANTON_NN NOT NULL,
       DIRECCION_EXACTA VARCHAR2(25)
          CONSTRAINT ADDRESS_DIRECCION_ NOT NULL,
       CONSTRAINT ADDRESS_FK PRIMARY KEY (ID_ADDRESS)
       USING INDEX
             TABLESPACE GE_IDX PCTFREE 20
             STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)
      ENABLE
)
LOGGING 
TABLESPACE GE_TBL
STORAGE (INITIAL 6144
        NEXT 6144
        MINEXTENTS 1
        MAXEXTENTS 5);
        
        
-- FOREING KEY        
ALTER TABLE ADDRESS
ADD CONSTRAINT ADDRESS_FK1 FOREIGN KEY(ID_ADDRESS)
REFERENCES PROVEEDOR(ID_PROVEEDOR)
ENABLE;        
