CREATE OR REPLACE PROCEDURE insertarBODEGA(pNOMBRE_BODEGA VARCHAR2,pPAIS VARCHAR2,
pPROVINCIA VARCHAR2,pCANTON VARCHAR2,pDIRECCION_EXACTA VARCHAR2, pNUMERO VARCHAR2)

IS
  VARID_DIRECCION NUMBER(10);
  VARID_TELEFONO NUMBER(10);
BEGIN
  VARID_DIRECCION := insertarDIRECCION(pPAIS,pPROVINCIA,pCANTON,pDIRECCION_EXACTA);
  VARID_TELEFONO := insertarTELEFONO(pNUMERO);
  INSERT INTO BODEGA(ID_BODEGA,ID_DIRECCION,ID_TELEFONO,NOMBREBODEGA)
  VALUES(S_BODEGA.NEXTVAL,VARID_DIRECCION,VARID_TELEFONO,upper(pNOMBRE_BODEGA));
  COMMIT;
END;