CREATE OR REPLACE PROCEDURE insertarPERSONA(pNOMBRE VARCHAR2,pCedula NUMBER,pAPELLIDO VARCHAR2,
pPAIS VARCHAR2,pPROVINCIA VARCHAR2,pCANTON VARCHAR2, pDIRECCION_EXACTA VARCHAR2,
pEMAIL VARCHAR2, pNUMERO VARCHAR2, pTIPO VARCHAR2)
IS
  VARID_DIRECCION NUMBER(10);
  VARID_TELEFONO NUMBER(10);
BEGIN
  VARID_DIRECCION := insertarDIRECCION(pPAIS,pPROVINCIA,pCANTON,pDIRECCION_EXACTA);
  VARID_TELEFONO := insertarTELEFONO(pNUMERO);
  
  INSERT INTO PERSONA(cedula, ID_DIRECCION,ID_TELEFONO,NOMBRE_PERSONA,APELLIDO_PERSONA, EMAIL_PERSONA,TIPO_PERSONA)
  VALUES(pCedula, VARID_DIRECCION,VARID_TELEFONO,upper(pNOMBRE),upper(pAPELLIDO),upper(pEMAIL),upper(pTIPO));   
  COMMIT;
END;