CREATE OR REPLACE PROCEDURE RESTOCK(pID_PRODUCTO NUMBER,pCANTIDAD NUMBER)
IS

VAR_CED_PERSONA NUMBER(10);
VAR_CANT_PRODUCTO NUMBER(10);
VAR_CANTIDAD NUMBER(10);
VAR_CANTIDAD_ACTUAL NUMBER(10);

BEGIN
  VAR_CED_PERSONA := -1;
  VAR_CANT_PRODUCTO := -1;
  VAR_CANTIDAD := -1;
  VAR_CANTIDAD_ACTUAL := -1;

  SELECT PERSONA INTO VAR_CED_PERSONA
  FROM PRODUCTO
  WHERE ID_PRODUCTO = pID_PRODUCTO;
  
  SELECT PRECIOUNITARIO INTO VAR_CANT_PRODUCTO
  FROM PRODUCTO
  WHERE ID_PRODUCTO = pID_PRODUCTO;
  
  VAR_CANTIDAD := (VAR_CANT_PRODUCTO * pCANTIDAD);
   
  INSERT INTO HISTORIAL_DE_COMPRAS(ID_HISTORIAL_DE_COMPRAS,ID_PERSONA,ID_PRODUCTO,CANTIDADPRODUCTOS,MONTO,TIPO_TRANSACCION)
  VALUES(S_HISTORIAL_DE_COMPRAS.NEXTVAL,VAR_CED_PERSONA,pID_PRODUCTO,pCANTIDAD,VAR_CANTIDAD,'DEBITO');
  
  SELECT CANTIDAD INTO VAR_CANTIDAD_ACTUAL
  FROM PRODUCTO
  WHERE ID_PRODUCTO = pID_PRODUCTO;
  
  UPDATE PRODUCTO
  SET CANTIDAD = VAR_CANTIDAD_ACTUAL + 500
  WHERE ID_PRODUCTO = pID_PRODUCTO;
  

END;