CREATE OR REPLACE FUNCTION retornaIDPERSONA(pNOMBRE VARCHAR2,pAPELLIDO VARCHAR2)
RETURN NUMBER
AS
  VARID_PERSONA NUMBER(10);
BEGIN
  VARID_PERSONA := 0;
  SELECT ID_PERSONA INTO VARID_PERSONA
  FROM PERSONA
  WHERE NOMBRE_PERSONA = upper(pNOMBRE) AND APELLIDO_PERSONA = upper(pAPELLIDO);
  RETURN VARID_PERSONA;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  VARID_PERSONA := 0;
  RETURN VARID_PERSONA;
-- si retorna 0 es porque la persona no esta ingresada ese error lo captan ya en java 

END;